spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://10.0.0.115/intel
    username: dbuser
    password: password
    driver-class-name: com.mysql.jdbc.Driver